"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getSupabase } from "../lib/supabase";

export default function Home(){
  const r=useRouter();
  const [session,setSession]=useState(null),[account,setAccount]=useState(null),[plans,setPlans]=useState([]),[plansError,setPlansError]=useState("");
  const [topic,setTopic]=useState(""),[title,setTitle]=useState(""),[language,setLanguage]=useState("ar"),[length,setLength]=useState("medium"),[article,setArticle]=useState(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{(async()=>{try{const s=getSupabase(),{data:{session}}=await s.auth.getSession();setSession(session||null);if(session){const x=await fetch("/api/account",{headers:{Authorization:`Bearer ${session.access_token}`}});const j=await x.json();if(x.ok)setAccount(j.user)}}catch(e){console.error(e)}try{const x=await fetch("/api/payment/plans",{cache:"no-store"});const j=await x.json();if(!x.ok)throw Error(j.error||"تعذر تحميل الباقات");setPlans(j.plans||[])}catch(e){setPlansError(e.message||"تعذر تحميل الباقات")}})()},[]);
  async function generate(){if(!session){r.push("/auth");return}setBusy(true);setMsg("");try{if(!topic.trim())throw Error("اكتب موضوع المقال أولًا");const x=await fetch("/api/generate",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({topic,title,language,length})}),j=await x.json();if(!x.ok)throw Error(j.error||"تعذر إنشاء المقال");setArticle(j.article);setMsg("تم إنشاء المقال وحفظه كمسودة.")}catch(e){setMsg(e.message)}finally{setBusy(false)}}
  const admin=account?.role==="admin";
  const btn={border:0,borderRadius:12,padding:"13px 22px",cursor:"pointer",fontWeight:800};
  return <main dir="rtl" style={{minHeight:"100vh",background:"#f7f8fc",color:"#111827",fontFamily:"Arial,sans-serif"}}>
    <nav style={{minHeight:72,background:"rgba(255,255,255,.96)",borderBottom:"1px solid #e5e7eb",display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,padding:"0 6%",boxSizing:"border-box",position:"sticky",top:0,zIndex:20,flexWrap:"wrap"}}>
      <button onClick={()=>r.push("/")} style={{background:"transparent",border:0,fontSize:24,fontWeight:900,cursor:"pointer",padding:0,color:"#4f46e5"}}>Rabtchi<span style={{color:"#111827"}}>Blogger</span></button>
      <div style={{display:"flex",gap:18,alignItems:"center",flexWrap:"wrap",fontSize:14}}><a href="#features" style={{color:"#374151",textDecoration:"none"}}>المميزات</a><a href="#how" style={{color:"#374151",textDecoration:"none"}}>كيف يعمل؟</a><a href="#pricing" style={{color:"#374151",textDecoration:"none"}}>الباقات</a>{session?<><span style={{fontWeight:700,color:admin?"#7c3aed":"#475569"}}>{admin?"👑 Admin":"👤 حسابي"}</span><button onClick={()=>r.push("/dashboard")} style={{...btn,padding:"10px 16px",background:"#111827",color:"#fff"}}>لوحة التحكم</button></>:<button onClick={()=>r.push("/auth")} style={{...btn,padding:"10px 16px",background:"#4f46e5",color:"#fff"}}>تسجيل الدخول</button>}</div>
    </nav>
    <section style={{padding:"82px 6% 70px",background:"linear-gradient(135deg,#eef2ff,#fff 55%,#f5f3ff)",textAlign:"center"}}><div style={{maxWidth:900,margin:"auto"}}><div style={{display:"inline-block",padding:"8px 15px",borderRadius:999,background:"#e0e7ff",color:"#4338ca",fontWeight:800,fontSize:13}}>منصة عربية احترافية لكتابة المقالات بالذكاء الاصطناعي</div><h1 style={{fontSize:"clamp(38px,6vw,68px)",lineHeight:1.1,margin:"22px 0 18px",letterSpacing:-2}}>حوّل فكرتك إلى <span style={{color:"#4f46e5"}}>مقال احترافي</span> في دقائق</h1><p style={{fontSize:20,lineHeight:1.8,color:"#4b5563",maxWidth:720,margin:"0 auto 30px"}}>أنشئ مقالات منظمة، احفظ مسوداتك، راجع المحتوى وصدّره بسهولة من حساب واحد.</p><div style={{display:"flex",justifyContent:"center",gap:12,flexWrap:"wrap"}}><button onClick={()=>session?document.getElementById("creator")?.scrollIntoView({behavior:"smooth"}):r.push("/auth")} style={{...btn,padding:"15px 28px",background:"#4f46e5",color:"#fff",fontSize:16}}>✨ ابدأ الآن</button><button onClick={()=>document.getElementById("pricing")?.scrollIntoView({behavior:"smooth"})} style={{...btn,padding:"15px 28px",background:"#fff",border:"1px solid #d1d5db",fontSize:16}}>عرض الباقات</button></div></div></section>
    <section id="features" style={{padding:"70px 6%"}}><h2 style={{textAlign:"center",fontSize:34}}>كل ما تحتاجه لإنشاء محتوى أفضل</h2><p style={{textAlign:"center",color:"#6b7280",marginBottom:38}}>تجربة واضحة من الفكرة حتى المقال الجاهز.</p><div style={{maxWidth:1100,margin:"auto",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:18}}>{[["✍️","إنشاء المقالات","حوّل فكرتك إلى مسودة منظمة."],["🌍","لغات متعددة","العربية وEnglish وFrançais."],["📚","إدارة المقالات","احتفظ بمسوداتك ومقالاتك."],["📤","تصدير آمن","نظام رصيد وحماية على الخادم."]].map(([i,t,d])=><div key={t} style={{background:"#fff",border:"1px solid #e5e7eb",borderRadius:18,padding:24,boxShadow:"0 8px 25px rgba(15,23,42,.05)"}}><div style={{fontSize:30}}>{i}</div><h3>{t}</h3><p style={{color:"#6b7280",lineHeight:1.7}}>{d}</p></div>)}</div></section>
    <section id="how" style={{padding:"65px 6%",background:"#111827",color:"#fff",textAlign:"center"}}><h2 style={{fontSize:34}}>كيف يعمل RabtchiBlogger؟</h2><div style={{maxWidth:1000,margin:"35px auto 0",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:20}}>{[["01","اكتب فكرتك","أدخل موضوع المقال."],["02","أنشئ المحتوى","اختر اللغة والطول."],["03","راجع المقال","عدّل المسودة كما تريد."],["04","صدّر وانشر","استخدم التصدير عند الجاهزية."]].map(([n,t,d])=><div key={n} style={{padding:20}}><div style={{fontSize:13,color:"#a5b4fc",fontWeight:900}}>{n}</div><h3>{t}</h3><p style={{color:"#cbd5e1",lineHeight:1.7}}>{d}</p></div>)}</div></section>
    <section id="creator" style={{padding:"75px 6%"}}><div style={{maxWidth:850,margin:"auto",background:"#fff",border:"1px solid #e5e7eb",borderRadius:24,padding:30,boxShadow:"0 15px 45px rgba(15,23,42,.08)"}}><h2 style={{marginTop:0}}>إنشاء مقال جديد</h2><p style={{color:"#6b7280"}}>ابدأ من موضوع واحد فقط.</p><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="مثال: أفضل طرق تحسين SEO للمدونات" style={{width:"100%",boxSizing:"border-box",padding:16,marginTop:18,borderRadius:12,border:"1px solid #d1d5db",fontSize:15}}/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان اختياري" style={{width:"100%",boxSizing:"border-box",padding:16,marginTop:12,borderRadius:12,border:"1px solid #d1d5db",fontSize:15}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginTop:12}}><select value={language} onChange={e=>setLanguage(e.target.value)} style={{padding:14,borderRadius:12,border:"1px solid #d1d5db"}}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select><select value={length} onChange={e=>setLength(e.target.value)} style={{padding:14,borderRadius:12,border:"1px solid #d1d5db"}}><option value="short">قصير</option><option value="medium">متوسط</option><option value="long">طويل</option></select></div><button disabled={busy} onClick={generate} style={{...btn,width:"100%",marginTop:16,padding:16,background:busy?"#9ca3af":"#4f46e5",color:"#fff",fontSize:16}}>{busy?"جارٍ إنشاء المقال...":"✨ إنشاء المقال بالذكاء الاصطناعي"}</button>{msg&&<div style={{marginTop:15,padding:14,borderRadius:10,background:"#f3f4f6"}}>{msg}</div>}{article&&<article style={{marginTop:28,borderTop:"1px solid #eee",paddingTop:24,lineHeight:1.9}}><h2>{article.title}</h2><div dangerouslySetInnerHTML={{__html:article.content}}/><button onClick={()=>r.push("/articles")} style={{...btn,background:"#111827",color:"#fff"}}>إدارة المقالات والتصدير</button></article>}</div></section>
    <section id="pricing" style={{padding:"75px 6%",background:"#f1f5f9",textAlign:"center"}}><h2 style={{fontSize:34,marginBottom:8}}>خطط وأسعار واضحة</h2><p style={{color:"#64748b",marginBottom:32}}>اختر الرصيد المناسب لك. الباقات تظهر مباشرة من قاعدة البيانات.</p>{plansError?<div style={{maxWidth:600,margin:"auto",padding:16,borderRadius:12,background:"#fff1f2",color:"#b91c1c"}}>{plansError}</div>:plans.length===0?<p style={{color:"#64748b"}}>جارٍ تحميل الباقات...</p>:<div style={{maxWidth:1050,margin:"auto",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:18}}>{plans.map((p,i)=><article key={p.id} style={{background:"#fff",border:i===1?"2px solid #4f46e5":"1px solid #e2e8f0",borderRadius:20,padding:28,boxShadow:"0 12px 35px rgba(15,23,42,.06)",position:"relative"}}>{i===1&&<div style={{position:"absolute",top:-13,right:"50%",transform:"translateX(50%)",background:"#4f46e5",color:"#fff",padding:"6px 14px",borderRadius:999,fontSize:12,fontWeight:800}}>الأكثر اختيارًا</div>}<h3 style={{fontSize:23,marginTop:4}}>{p.name}</h3><div style={{fontSize:38,fontWeight:900,color:"#111827"}}>${Number(p.price_usd).toFixed(2)}</div><p style={{fontSize:18,fontWeight:800,color:"#4f46e5"}}>{p.article_credits} رصيد مقال</p><button onClick={()=>r.push(session?"/pricing":"/auth")} style={{...btn,width:"100%",background:"#111827",color:"#fff"}}>اختيار الباقة</button></article>)}</div>}<button onClick={()=>r.push("/pricing")} style={{...btn,marginTop:28,background:"#4f46e5",color:"#fff"}}>إدارة الباقات والدفع</button></section>
    <footer style={{padding:"30px 6%",background:"#0f172a",color:"#cbd5e1",textAlign:"center"}}>© 2026 RabtchiBlogger — منصة إنشاء المقالات بالذكاء الاصطناعي</footer>
  </main>
}
