import crypto from "crypto";
import { createClient } from "@supabase/supabase-js";

const algorithm = "aes-256-gcm";
function key(){const raw=process.env.BLOGGER_TOKEN_ENCRYPTION_KEY||"";if(!/^[0-9a-fA-F]{64}$/.test(raw))throw Error("BLOGGER_TOKEN_ENCRYPTION_KEY must be a 64-character hex key");return Buffer.from(raw,"hex")}
export function encryptToken(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv(algorithm,key(),iv),encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return `${iv.toString("hex")}.${cipher.getAuthTag().toString("hex")}.${encrypted.toString("hex")}`}
export function decryptToken(value){const [ivHex,tagHex,dataHex]=String(value||"").split(".");if(!ivHex||!tagHex||!dataHex)throw Error("Invalid Blogger token");const decipher=crypto.createDecipheriv(algorithm,key(),Buffer.from(ivHex,"hex"));decipher.setAuthTag(Buffer.from(tagHex,"hex"));return Buffer.concat([decipher.update(Buffer.from(dataHex,"hex")),decipher.final()]).toString("utf8")}
export function adminServer(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw Error("Supabase server credentials are missing");return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function bloggerAccessToken(refreshToken){const id=process.env.GOOGLE_CLIENT_ID,secret=process.env.GOOGLE_CLIENT_SECRET;if(!id||!secret)throw Error("Google Blogger OAuth credentials are not configured");const body=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:refreshToken,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const j=await r.json();if(!r.ok)throw Error(j.error_description||"Unable to refresh Blogger access token");return j.access_token}
